spa/plugins/alsa/alsa-monitor.c
spa/plugins/alsa/alsa-source.c
spa/plugins/v4l2/v4l2-monitor.c
spa/plugins/v4l2/v4l2-source.c
src/modules/module-jack.c
src/modules/module-protocol-native/connection.c

clangs complains about an uint32 compared to < 0:
warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
So remove these comparisos and an uint32 never will be less than 0.
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>

Fix clang warnings about comparing uint32 < 0

---

spa/include/spa/meson.build

When compiling some application and include spa/loop.h, it needs hook.h,
so install it.
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>

spa/include/meson: Install hook.h

---

src/modules/module-flatpak.c
src/modules/spa/spa-monitor.c
src/pipewire/rtkit.c

Clang static analyzer reported couple of memory leaks and a user after free issue. This pull request fixes them. Each commit fixes one issue.

Fix memory issues reported by clang static analyzer

---

src/tools/pipewire-cli.c

read() returns ssize_t where a negative number is used for errors.
The value was read into a size_t and then checked for <0.
Change to ssize_t to handle the negative number.

cli: use a signed type for return value

---

meson.build
meson_options.txt

As mentioned in #18 it's annoying to have automagic dependencies, e.g. if one uses a source based distro, where it's desirable to enable such things via flags and not have these determined automagically, depending on what is installed on the host

meson.build: remove automagic docs and manpages

---

README

Add a short paragraph to indicate that there are two methods
to build pipewire.
Signed-off-by: Harry van Haaren <harryhaaren@gmail.com>

readme: add section on building with make or meson

---

spa/plugins/v4l2/v4l2-utils.c

Recent kernels add metadata devices next to UVC capture devices. These have the V4L2_CAP_DEVICE_CAPS and V4L2_CAP_VIDEO_CAPTURE flags set in capabilities, but V4L2_CAP_VIDEO_CAPTURE unset in device_caps.
Check device caps as well to determine video capture capability. Fixes #37.

v4l2: check device caps

---

spa/include/spa/support/log.h
src/pipewire/log.h

Clang++ (and g++) don't define __STDC_VERSION__ which results in
include/spa/support/log.h:101:5: error: '__STDC_VERSION__' is not defined, evaluates to 0 [-Werror,-Wundef]
#if __STDC_VERSION__ >= 199901L
include/pipewire/log.h:64:5: error: '__STDC_VERSION__' is not defined, evaluates to 0 [-Werror,-Wundef]
#if __STDC_VERSION__ >= 199901L
so check if __STDC_VERSION__ is defined before comparing.
Also, include/feature.h additionally defines __USE_ISOC99 (and
__USE_ISOC11 for C11 extension), so check these as well.

__STDC_VERSION__ may be undefined

---

meson.build

PipeWire 0.2.0 is not API and ABI compatible with previous versions and we should let people know about that.

Bump apiversion and soversion for PW 0.2.x

---

meson.build
pkgconfig/libpipewire.pc.in
pkgconfig/meson.build
src/modules/spa/meson.build
src/pipewire/meson.build

Also please see https://github.com/PipeWire/pipewire/issues/77. If we keep using api version as suffix for library name, everyone will have to search for libpipewire-0.1 for old PW, then libpipewire-0.2 for current PW and in future for libpipewire-0.3 and so on, which is not good and makes supporting multiple PW versions complicated.

Drop api version suffix from library name

---

spa/include/spa/utils/defs.h

By using __typeof__ instead of typeof:
/usr/include/pipewire/array.h:85:11: error: use of undeclared identifier 'typeof'; did you mean 'typeid'?
alloc = SPA_MAX(alloc, arr->extend);

Fix build with clang

---

meson.build
pw-uninstalled.sh

This makes it easier to run PipeWire from the build environment

meson: Add an uninstalled target and script

---

spa/plugins/bluez5/a2dp-sink.c

This gets rid of a compiler warning.

bluez5: remove an unused variable

---

autogen.sh

An unquoted $@ will break for arguments with spaces in their names. Unquoted $@ will work until it doesn't, and then it can be tricky to track down exactly what went wrong. Using "$@" will save someone some headache in the future.

Quote "$@" in autogen.sh

---

.editorconfig
src/gst/.editorconfig

These files help editors choose the correct coding style
conventions, mostly useful for the indentation style
Pipewire uses tab characters of size 8 in all of its codebase
except in the meson files and in the gstreamer plugins,
which use 2-space indentation

add .editorconfig files

---

src/pipewire/remote.c

pw_proxy_new() expects a size for its user data structure
as the last argument, not a proxy version

remote: use 0 for pw_proxy_new() user_data_size argument

---

meson.build
spa/meson.build
spa/plugins/meson.build
spa/plugins/support/meson.build
spa/plugins/test/meson.build
spa/plugins/videotestsrc/meson.build

This allows finding dependencies conditionally, only when the enabled features actually need them.
Examples of scenarios that are being fixed:
* compile with -Dv4l2=false -> libv4l2 doesn't need to be installed in the system
* compile with -Dbluez5=true -> bluez and sbc MUST be installed in the system
* compile with -Dspa-plugins=false and -Dpipewire-alsa=true -> alsa must be installed and found
* compile with -Dpipewire-pulseaudio=false and -Dgstreamer=false -> glib doesn't need to be installed
This also removes some dependencies that were being found but not used, like X11, libva and avfilter

meson: find dependencies only when necessary + some other dependency-related fixes

---

spa/tests/meson.build
src/tests/meson.build

meson < 0.46 does not allow two targets to share the same name;
meson >= 0.46 relaxes that requirement, but I see no reason to require
a new version of meson just for this

meson: prefix the names of the tests so that they are unique in the tree

---

src/daemon/main.c

On some toolchains/architectures, a char with -1 value is not equal
to the integer -1, resulting in this code to think that it got
an unrecognized command line option

daemon: getopt returns int, declare it as such to avoid comparison issues

---

spa/plugins/v4l2/v4l2-utils.c

If VIDIOC_QUERYCAP fails, or V4L2_CAP_VIDEO_CAPTURE is not set,
spa_v4l2_open should close the port file descriptor again.

v4l2: do not keep non-capture devices open

---

spa/include/spa/meson.build

This header is missing from installations and a simple #include <pipewire/pipewire.h> fails

spa: install pod/vararg.h

---

src/modules/module-link-factory.c

harmless, but leads to a wrong error message being printed

module-link-factory: fix wrong goto label

---

src/daemon/main.c

Depending on the compiler configuration 'char' may be an unsigned type
which will not work as expected.
Signed-off-by: Matthias Fend <matthias.fend@wolfvision.net>

daemon: use correct type for getopt_long() return value

---

spa/plugins/bluez5/a2dp-source.c
spa/plugins/bluez5/bluez5-device.c
spa/plugins/bluez5/bluez5-monitor.c
spa/plugins/bluez5/meson.build

This PR adds an a2dp-source plugin node to play audio from bluetooth sources via a2dp.
This can be easily tested with a phone and bluetooth speaker by doing the following:
- Run the pipewire daemon.
- Connect the bluetooth speaker to your PC using the bluetoothctl tool (an a2dp-sink node should have been created).
- Connect the smart phone via bluetooth to your PC using the bluetoothctl tool (an a2dp-source node should have been created).
- Run the pipewire-cli tool.
- Connect to the pipewire daemon by entering the connect command.
- Create a link between the a2dp-source and a2dp-sink nodes with the create-link <src_id> <src_port_id> <sink_id> <sink_port_id> command.
- Play a song in your phone and it should be played in the bluetooth speaker.
Note that this has only been tested using a …

bluez5: add a2dp-source plugin

---

spa/meson.build
spa/plugins/v4l2/meson.build

It's not used anywhere right now.

remove libv4l2 dependency

---

src/pipewire/core.c

pw_core_find_format() is currently broken when one of the ports is already
active: The format of the active port is used and the other port is
completely ignored.
As a result, the autolink module may try to link a new port to the first
already active port even if the formats do not match.
To fix this, use the format of the active port as a filter when enumerating
the format of the other port.

core: fix pw_core_find_format() for active ports

---

spa/include/spa/utils/hook.h
src/pipewire/private.h

Introduce spa_hook_list_call_simple_safe() as a new helper that uses
spa_list_for_each_safe() and use it for pw_node_events_* This way multiple
threads can iterate at the same time and, if only one thread is active, the
current list entry can be safely removed (e.g. in
pw_node_events_destroy()).
Without this the node listener_list may be corrupted when the main and data
loop iterate over the list at the same time (See #143).
This works for me to fix #143 but I'm not sure if this is the correct fix.
This only works if two assumptions are correct:
1. The data loop does not access the  listener_list when the functions that modify the list are called in the main loop (e.g. destroy).
2. All functions do not modify the list except to remove the current element.
This seem to be the case but I …

node: use spa_list_for_each_safe() for pw_node_events_*

---

src/gst/gstpipewiresrc.c

This is necessary for 'do-timestamp' to work if the source provides no
timestamps. Without this, the timestamp from the first use will remain,
because the basesrc only overwrites timestamps that are
GST_CLOCK_TIME_NONE.

gstpipewiresrc: clear timestamps when processing a buffer

---

.travis.yml

On the CI docker image, there is no "which" command,
so meson cannot be detected.

travis: fix runing autogen.sh after changes to detect meson

---

.travis.yml
check_missing_headers.sh

This will prevent in the future the situation where we add a new header but we forget to list it in meson.build

travis: run make install and check for headers that have not been installed

---

src/gst/gstpipewiredeviceprovider.c
src/gst/gstpipewiredeviceprovider.h

self->type is needed in registry_event_global() so it must be set in
gst_pipewire_device_provider_probe() as well.
self->devices is initialized as NULL when probing is started. So it should
be just a simple GList* pointer.
Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>

deviceprovider: fix probing without starting

---

spa/include/spa/pod/builder.h
spa/plugins/alsa/alsa-monitor.c
spa/plugins/alsa/alsa-utils.c
spa/plugins/v4l2/v4l2-monitor.c
spa/plugins/v4l2/v4l2-source.c
spa/plugins/v4l2/v4l2-utils.c

spa_pod_builder_add() is a va_args function that is terminated by a NULL
argument. The last argument must be a pointer type, because otherwise
checking for a NULL pointer can fail.
The __attribute__((__sentinel__)) prints a compiler warning, if the last
argument of a call to spa_pod_builder_add() is not a pointer type.
Fix all sentinel warnings by replacing all integer type 0 with pointer
type NULL in calls to spa_pod_builder_add().

builder: fix calls to builder_add that are not terminated by NULL

---

spa/plugins/audioconvert/fmtconvert.c

This allows picking F32LE as the default format on links that have
no restriction and it avoids failing negotiation when the restricted
end cannot handle S16/F32/F32P
For instance this pipeline would previously fail:
```
audio-dsp mode=merge ! audio-dsp mode=convert ! alsa-sink
old negotiation:     S16LE                   S24_32LE
new negotiation:     F32LE                   S24_32LE
```
The link between the audio-dsp nodes has no restriction, so previously
it would negotiate S16LE, which would then fail to negotiate with alsa-sink
because fmtconvert does not know how to convert S16LE to S24_32LE directly.
With this change, the middle link negotiates to F32LE, which can be
converted to anything.

audioconvert/fmtconvert: assume F32 on the other port when listing formats

---

.travis.yml

It turns out that indentation matters...
My apologies that it took so long to figure this out
PS: the build still fails, but this is because some optional spa plugins have not been updated to API changes. I have verified that it works when these plugins are disabled. IMHO, the CI should build all code in the repository and find these issues, so I have kept these plugins enabled.

travis: fix the build script

---

spa/include/spa/utils/names.h
spa/plugins/bluez5/bluez5-device.c
spa/plugins/bluez5/bluez5-monitor.c
spa/plugins/bluez5/meson.build
spa/plugins/bluez5/plugin.c
spa/plugins/bluez5/sco-sink.c
spa/plugins/bluez5/sco-source.c

This PR adds a first version of both sco-sink and sco-source nodes to handle both HSP/HFP bluetooth profiles.
I only tested these nodes with my HFP bluetooth headset and an old version of the `work` branch using 2 custom gstreamer elements. Both nodes mostly work with that old branch, however, there are still audio issues that don't seem to be related to the nodes implementation (the a2dp nodes have the same problem).
The purpose of this MR is mostly to avoid updating some of my already implemented bluetooth logic.
Here is the branch I used to test them: https://github.com/julianbouzas/pipewire/commits/endpoint
Both elements can be tested as follows:
gst-launch-1.0 audiotestsrc ! pwaudiosink path=<sco-sink-id>
gst-launch-1.0 pwaudiosrc path=<sco-source-id> ! wavenc ! filesink …

Add bluetooth sco-sink and sco-source nodes

---

meson.build

Features are used from 0.44 but min version is specified as 0.42.
Bump min version to 0.44.
Signed-off-by: Matt Porter <mporter@konsulko.com>

meson.build: fix meson version warning

---

src/modules/module-protocol-native.c

Getting SO_PEERSEC on distributions that do not use a LSM by default,
results always in a "protocol error", which is just annoying and not
a real problem for pipewire's operation.

protocol-native: downgrade getsockopt SO_PEERSEC error to warning

---

src/tools/pipewire-cli.c

so that you can now write, for example, "list-objects Node"
and see only the nodes, instead of seeing all the objects, which
can be hundreds...

pipewire-cli: add interface filter in the list-objects command

---

spa/plugins/bluez5/a2dp-sink.c

This PR fixes an infinite loop that always happens when playing audio with a2dp-sink.
Steps to reproduce:
- Run pipewire with the example media-session
- Connect a bluetooth speaker and wait for the a2dp-sink node to be created
- Try to play audio using the example audio-src executable
- No audio is played and the a2dp-sink gets into an infinite loop state
The audio plays without issues if we use this patch

Fix infinite loop in a2dp-sink

---

spa/include/spa/utils/keys.h
spa/plugins/bluez5/bluez5-device.c
spa/plugins/bluez5/defs.h

We need to expose the bluetooth profile in the nodes so that external
applications know how to handle them.

bluez: set bluez profile property when emitting node

---

spa/plugins/audioconvert/audioadapter.c

Currently it is not possible for a user to select a specific audio format when playing audio on a device that supports multiple audio formats... this change solves this problem by changing the audioadapter node to store internally a format previously set with `SPA_PARAM_Format`, and using it as a filter when negotiating.

Audioadapter store format

---

pipewire-alsa/alsa-plugins/pcm_pipewire.c

Make the allowed buffer-size reflect period_bytes and MIN_BUFFERS/MAX_BUFFERS.
This will allow for lower audio-latency.

alsa-plugin: change hw-constraint on buffer-size
